workspace(name = "codegen_example")

# Load Python rules
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Rules for Python
http_archive(
    name = "rules_python",
    sha256 = "0a8003b044294d7840ac7d9d73eef05d6ceb682d7516781a4ec62eeb34702578",
    strip_prefix = "rules_python-0.24.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.24.0/rules_python-0.24.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()

# Rules for Rust (for the Rust example)
http_archive(
    name = "rules_rust",
    integrity = "sha256-T5kWGIHS38tSNIc7f5fIiwMCOZ3SwPUGCKAjQOLGgdw=",
    urls = ["https://github.com/bazelbuild/rules_rust/releases/download/0.46.0/rules_rust-v0.46.0.tar.gz"],
)

load("@rules_rust//rust:repositories.bzl", "rules_rust_dependencies", "rust_register_toolchains")

rules_rust_dependencies()

rust_register_toolchains(
    edition = "2021",
    versions = ["1.75.0"],
)