# Template files
filegroup(
    name = "all_templates",
    srcs = glob(["*.j2"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "header.h.j2",
    srcs = ["header.h.j2"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "constants.rs.j2",
    srcs = ["constants.rs.j2"],
    visibility = ["//visibility:public"],
)